-- Comprehensive Sample Odisha Culture Questions for Question Bank
-- This file contains 50-60 sample questions covering various aspects of Odisha's culture, traditions, history, geography, festivals, arts, and heritage
-- Run this in your Supabase SQL Editor to populate the question bank
-- All questions have exam_id = NULL, making them available for use in any exam

-- ============================================
-- Category 1: Temples & Architecture
-- ============================================

INSERT INTO questions (exam_id, question_text, option_a, option_b, option_c, option_d, correct_answer, points, category, difficulty_level, tags, explanation) VALUES
(NULL, 'The Rajarani Temple in Bhubaneswar is famous for its unique architectural style. What is it primarily known for?', 'Its circular design', 'Its absence of a deity', 'Its golden dome', 'Its underground chambers', 'B', 1, 'Temples & Architecture', 'medium', '["Rajarani Temple", "Bhubaneswar", "Architecture", "Temples"]'::jsonb, 'The Rajarani Temple is unique because it does not house any deity. It is purely an architectural marvel, known for its beautiful carvings and sculptures.'),
(NULL, 'Which temple in Odisha is known for its "Deul" style of architecture and is considered one of the oldest temples in Bhubaneswar?', 'Mukteswar Temple', 'Parasurameswar Temple', 'Lingaraj Temple', 'Rajarani Temple', 'B', 1, 'Temples & Architecture', 'hard', '["Parasurameswar", "Deul Architecture", "Bhubaneswar", "Temples"]'::jsonb, 'Parasurameswar Temple, built in the 7th century, is one of the oldest temples in Bhubaneswar and showcases the early Deul style of Odishan temple architecture.'),
(NULL, 'The Jagannath Temple in Puri is one of the Char Dham pilgrimage sites. How many times is the temple rebuilt with new wood?', 'Every 8 years', 'Every 12 years', 'Every 19 years', 'Every 25 years', 'C', 1, 'Temples & Architecture', 'hard', '["Jagannath Temple", "Nabakalebara", "Puri", "Temples"]'::jsonb, 'The Nabakalebara ritual occurs every 19 years when the wooden idols of Jagannath, Balabhadra, Subhadra, and Sudarshan are replaced with new ones carved from a special neem tree.'),
(NULL, 'Which architectural feature is characteristic of Odishan temple architecture and represents the cosmic mountain?', 'Shikhara', 'Mandapa', 'Garbhagriha', 'Jagamohana', 'A', 1, 'Temples & Architecture', 'medium', '["Temple Architecture", "Shikhara", "Odishan Architecture"]'::jsonb, 'The Shikhara (tower) in Odishan temple architecture represents Mount Meru, the cosmic mountain, and is the most prominent feature of these temples.'),
(NULL, 'The Mukteswar Temple is often called the "Gem of Odishan Architecture". What is its most distinctive feature?', 'Its golden spire', 'Its torana (arched gateway)', 'Its underground sanctum', 'Its circular design', 'B', 1, 'Temples & Architecture', 'medium', '["Mukteswar Temple", "Torana", "Architecture", "Bhubaneswar"]'::jsonb, 'The Mukteswar Temple is famous for its elaborately carved torana (arched gateway), which is considered one of the finest examples of Odishan temple architecture.'),
(NULL, 'Which temple in Odisha is dedicated to Lord Shiva and is known for its 64 Yogini shrines?', 'Hirapur Chausath Yogini Temple', 'Lingaraj Temple', 'Mukteswar Temple', 'Parasurameswar Temple', 'A', 1, 'Temples & Architecture', 'hard', '["Hirapur", "Yogini Temple", "Shiva", "Temples"]'::jsonb, 'The Hirapur Chausath Yogini Temple near Bhubaneswar is a circular temple dedicated to 64 Yoginis, representing the feminine aspects of divinity.'),
(NULL, 'The Konark Sun Temple is designed as a chariot. How many horses are depicted pulling this chariot?', '5 horses', '6 horses', '7 horses', '8 horses', 'C', 1, 'Temples & Architecture', 'hard', '["Konark", "Sun Temple", "Chariot", "Architecture"]'::jsonb, 'The Konark Sun Temple is designed as a massive chariot with 7 horses, representing the 7 days of the week, pulling the sun god''s chariot.'),
(NULL, 'Which temple in Odisha is known for its erotic sculptures and is part of the "Temple City" of Bhubaneswar?', 'Lingaraj Temple', 'Mukteswar Temple', 'Rajarani Temple', 'Parasurameswar Temple', 'C', 1, 'Temples & Architecture', 'medium', '["Rajarani Temple", "Sculptures", "Bhubaneswar", "Temples"]'::jsonb, 'The Rajarani Temple is famous for its intricate sculptures, including some erotic carvings, and is considered one of the architectural gems of Bhubaneswar.'),

-- ============================================
-- Category 2: Festivals
-- ============================================

(NULL, 'Kartika Purnima is an important festival in Odisha. What is it primarily associated with?', 'Harvest celebration', 'Boat racing in Chilika Lake', 'Temple visits and lighting lamps', 'New Year celebration', 'C', 1, 'Festivals', 'medium', '["Kartika Purnima", "Festivals", "Chilika"]'::jsonb, 'Kartika Purnima is celebrated with great devotion, involving temple visits, lighting lamps, and taking holy dips. It also marks the beginning of the boating season in Chilika Lake.'),
(NULL, 'During Rath Yatra, the three chariots of Jagannath, Balabhadra, and Subhadra are pulled to which temple?', 'Gundicha Temple', 'Lingaraj Temple', 'Mukteswar Temple', 'Konark Temple', 'A', 1, 'Festivals', 'medium', '["Rath Yatra", "Jagannath", "Gundicha Temple", "Puri"]'::jsonb, 'During Rath Yatra, the deities are taken from Jagannath Temple to Gundicha Temple, where they stay for 7 days before returning.'),
(NULL, 'What is the traditional name for the return journey of Rath Yatra when the deities come back to the main temple?', 'Bahuda Yatra', 'Snana Yatra', 'Chandan Yatra', 'Nabakalebara', 'A', 1, 'Festivals', 'hard', '["Rath Yatra", "Bahuda Yatra", "Jagannath", "Festivals"]'::jsonb, 'Bahuda Yatra is the return journey of the deities from Gundicha Temple back to the Jagannath Temple after their 7-day stay.'),
(NULL, 'Nuakhai is celebrated with the offering of the first grain of the season. What grain is traditionally offered?', 'Rice', 'Wheat', 'Millet', 'Corn', 'A', 1, 'Festivals', 'easy', '["Nuakhai", "Harvest Festival", "Rice", "Western Odisha"]'::jsonb, 'Nuakhai is a harvest festival where the first grain of rice from the new harvest is offered to the goddess, followed by family celebrations.'),
(NULL, 'Raja Parba is a unique three-day festival. On which day do women and girls celebrate by not doing household work?', 'First day (Pahili Raja)', 'Second day (Raja Sankranti)', 'Third day (Basi Raja)', 'All three days', 'D', 1, 'Festivals', 'medium', '["Raja Parba", "Women Festival", "Fertility Festival"]'::jsonb, 'During all three days of Raja Parba, women and girls take a break from household work, wear new clothes, apply alta (red dye) on their feet, and enjoy swings.'),
(NULL, 'Snana Yatra is a festival where the deities are given a ceremonial bath. In which month does it occur?', 'Jyestha (May-June)', 'Ashadha (June-July)', 'Shravana (July-August)', 'Bhadraba (August-September)', 'A', 1, 'Festivals', 'hard', '["Snana Yatra", "Jagannath", "Festivals", "Puri"]'::jsonb, 'Snana Yatra occurs on the full moon day of Jyestha month, where the deities are given a ceremonial bath with 108 pots of water.'),
(NULL, 'Chandan Yatra is a 42-day festival in Puri. What is it primarily known for?', 'Sandalwood paste application', 'Boat festival in Narendra Tank', 'Flower decoration', 'Music and dance performances', 'B', 1, 'Festivals', 'hard', '["Chandan Yatra", "Jagannath", "Narendra Tank", "Festivals"]'::jsonb, 'Chandan Yatra is a 42-day festival where the deities are taken in boats to the Narendra Tank for a boat festival, along with application of sandalwood paste.'),
(NULL, 'Which festival in Odisha marks the beginning of the agricultural year and is celebrated with great enthusiasm in rural areas?', 'Nuakhai', 'Raja Parba', 'Makar Sankranti', 'Pana Sankranti', 'D', 1, 'Festivals', 'medium', '["Pana Sankranti", "New Year", "Festivals", "Odisha"]'::jsonb, 'Pana Sankranti (Maha Vishuva Sankranti) marks the Odia New Year and the beginning of the agricultural season, celebrated with pana (a sweet drink) and various rituals.'),

-- ============================================
-- Category 3: Language & Literature
-- ============================================

(NULL, 'In which year was Odia recognized as a classical language by the Government of India?', '2012', '2013', '2014', '2015', 'C', 1, 'Language & Literature', 'medium', '["Odia Language", "Classical Language", "Literature"]'::jsonb, 'Odia was recognized as the 6th classical language of India in 2014, joining Sanskrit, Tamil, Telugu, Kannada, and Malayalam.'),
(NULL, 'Who wrote the famous Odia epic "Mahabharata" in Odia language, making it accessible to common people?', 'Sarala Das', 'Jagannath Das', 'Balaram Das', 'Achyutananda Das', 'A', 1, 'Language & Literature', 'medium', '["Sarala Das", "Mahabharata", "Epic", "Literature"]'::jsonb, 'Sarala Das, a 15th-century poet, translated and adapted the Mahabharata into Odia, making it the first major literary work in the language.'),
(NULL, 'Which famous Odia poet is known as "Kabi Samrat" (Emperor of Poets) and wrote in the kavya style?', 'Upendra Bhanja', 'Radhanath Ray', 'Fakir Mohan Senapati', 'Gangadhar Meher', 'A', 1, 'Language & Literature', 'medium', '["Upendra Bhanja", "Kabi Samrat", "Poetry", "Literature"]'::jsonb, 'Upendra Bhanja (1670-1720) is known as "Kabi Samrat" and is famous for his kavya poetry, particularly "Baidehisha Bilasa" and "Lavanyabati".'),
(NULL, 'Who is considered the father of modern Odia prose and wrote the famous novel "Chha Mana Atha Guntha"?', 'Fakir Mohan Senapati', 'Radhanath Ray', 'Madhusudan Das', 'Gopabandhu Das', 'A', 1, 'Language & Literature', 'easy', '["Fakir Mohan Senapati", "Modern Prose", "Chha Mana Atha Guntha", "Literature"]'::jsonb, 'Fakir Mohan Senapati (1843-1918) is considered the father of modern Odia prose. His novel "Chha Mana Atha Guntha" (Six Acres and a Third) is a masterpiece of Indian literature.'),
(NULL, 'Which Odia poet is known for his work "Chilika" and is considered one of the pioneers of modern Odia poetry?', 'Radhanath Ray', 'Upendra Bhanja', 'Gangadhar Meher', 'Madhusudan Rao', 'A', 1, 'Language & Literature', 'hard', '["Radhanath Ray", "Chilika", "Modern Poetry", "Literature"]'::jsonb, 'Radhanath Ray (1848-1908) is known for his poem "Chilika", which describes the beauty of Chilika Lake. He is considered a pioneer of modern Odia poetry.'),
(NULL, 'The Odia Ramayana was translated by which famous poet, making it one of the earliest translations?', 'Balaram Das', 'Jagannath Das', 'Sarala Das', 'Achyutananda Das', 'B', 1, 'Language & Literature', 'hard', '["Jagannath Das", "Ramayana", "Translation", "Literature"]'::jsonb, 'Jagannath Das (1490-1550) translated the Ramayana into Odia, creating "Jagannath Das''s Ramayana", which is widely read and respected.'),
(NULL, 'Which Odia writer is known for his social reform works and was a key figure in the Odia language movement?', 'Gopabandhu Das', 'Madhusudan Das', 'Fakir Mohan Senapati', 'Radhanath Ray', 'A', 1, 'Language & Literature', 'medium', '["Gopabandhu Das", "Social Reform", "Literature", "Freedom Fighter"]'::jsonb, 'Gopabandhu Das (1877-1928) was a social reformer, freedom fighter, and writer who played a crucial role in the Odia language movement and social reforms.'),
(NULL, 'Who wrote the famous Odia novel "Basanti" and is considered one of the early modern Odia novelists?', 'Kalindi Charan Panigrahi', 'Gopinath Mohanty', 'Fakir Mohan Senapati', 'Manoranjan Das', 'A', 1, 'Language & Literature', 'hard', '["Kalindi Charan Panigrahi", "Basanti", "Novel", "Literature"]'::jsonb, 'Kalindi Charan Panigrahi (1901-1991) wrote "Basanti" and other novels, contributing significantly to modern Odia literature.'),

-- ============================================
-- Category 4: Traditional Arts & Dance
-- ============================================

(NULL, 'Odissi dance is one of the eight classical dance forms of India. How many basic poses or "bhangas" are there in Odissi?', 'Three bhangas', 'Four bhangas', 'Five bhangas', 'Six bhangas', 'A', 1, 'Traditional Arts', 'hard', '["Odissi Dance", "Bhangas", "Classical Dance"]'::jsonb, 'Odissi dance has three basic bhangas (poses): Abhanga (slight bend), Tribhanga (triple bend), and Atibhanga (extreme bend).'),
(NULL, 'Pattachitra paintings traditionally depict stories from which epic?', 'Ramayana', 'Mahabharata', 'Both Ramayana and Mahabharata', 'Puranas and religious stories', 'D', 1, 'Traditional Arts', 'medium', '["Pattachitra", "Traditional Art", "Painting", "Odisha"]'::jsonb, 'Pattachitra paintings traditionally depict stories from Puranas, religious texts, and mythological stories, often featuring Jagannath, Krishna, and other deities.'),
(NULL, 'Gotipua dance is performed by young boys. What does "Gotipua" mean in Odia?', 'Young dancer', 'Single boy', 'Boy dressed as girl', 'Little performer', 'B', 1, 'Traditional Arts', 'medium', '["Gotipua", "Dance", "Traditional", "Odisha"]'::jsonb, 'Gotipua means "single boy" in Odia. These young boys dress as girls and perform acrobatic dance, which is considered a precursor to modern Odissi dance.'),
(NULL, 'Which traditional Odia art form involves creating intricate designs by cutting and pasting colored cloth pieces?', 'Pattachitra', 'Applique work', 'Silver filigree', 'Stone carving', 'B', 1, 'Traditional Arts', 'medium', '["Applique", "Handicraft", "Traditional Art", "Pipili"]'::jsonb, 'Applique work, particularly famous in Pipili, involves cutting and stitching colored cloth pieces to create beautiful designs, often used for umbrellas, canopies, and wall hangings.'),
(NULL, 'Sambalpuri dance is a folk dance form. Which region of Odisha is it primarily associated with?', 'Coastal Odisha', 'Western Odisha', 'Northern Odisha', 'Southern Odisha', 'B', 1, 'Traditional Arts', 'easy', '["Sambalpuri Dance", "Folk Dance", "Western Odisha"]'::jsonb, 'Sambalpuri dance is a vibrant folk dance form from Western Odisha, particularly from the Sambalpur region, performed during festivals and celebrations.'),
(NULL, 'Which traditional art form of Odisha involves creating beautiful designs on palm leaves using a stylus?', 'Pattachitra', 'Talapatra Chitra', 'Stone carving', 'Wood carving', 'B', 1, 'Traditional Arts', 'medium', '["Talapatra Chitra", "Palm Leaf", "Traditional Art"]'::jsonb, 'Talapatra Chitra involves engraving intricate designs and texts on palm leaves using a stylus, a traditional art form that has been practiced in Odisha for centuries.'),
(NULL, 'The traditional "Danda Nacha" is performed during which festival?', 'Durga Puja', 'Nuakhai', 'Raja Parba', 'Dussehra', 'D', 1, 'Traditional Arts', 'hard', '["Danda Nacha", "Folk Dance", "Dussehra", "Western Odisha"]'::jsonb, 'Danda Nacha is a traditional folk dance performed during Dussehra in Western Odisha, where performers dance with sticks (danda) in a rhythmic pattern.'),
(NULL, 'Which classical dance form of Odisha is known for its graceful movements and expressions, often depicting stories of Radha and Krishna?', 'Odissi', 'Gotipua', 'Chhau', 'Sambalpuri', 'A', 1, 'Traditional Arts', 'easy', '["Odissi Dance", "Classical Dance", "Radha Krishna"]'::jsonb, 'Odissi is the classical dance form of Odisha, known for its graceful movements, intricate footwork, and expressive storytelling, often depicting stories of Radha and Krishna.'),

-- ============================================
-- Category 5: Geography
-- ============================================

(NULL, 'Which is the smallest district in Odisha by area?', 'Jagatsinghpur', 'Jajpur', 'Bhadrak', 'Kendrapara', 'A', 1, 'Geography', 'hard', '["Districts", "Geography", "Jagatsinghpur"]'::jsonb, 'Jagatsinghpur is the smallest district in Odisha by area, located in the coastal region.'),
(NULL, 'The Hirakud Dam, one of the longest dams in the world, is built on which river?', 'Mahanadi', 'Brahmani', 'Baitarani', 'Subarnarekha', 'A', 1, 'Geography', 'medium', '["Hirakud Dam", "Mahanadi", "Geography", "Dams"]'::jsonb, 'The Hirakud Dam is built on the Mahanadi River near Sambalpur. It is one of the longest dams in the world and provides irrigation and hydroelectric power.'),
(NULL, 'Which district in Odisha is known as the "Steel City" of Odisha?', 'Rourkela', 'Sambalpur', 'Cuttack', 'Bhubaneswar', 'A', 1, 'Geography', 'easy', '["Rourkela", "Steel City", "Geography", "Industries"]'::jsonb, 'Rourkela is known as the "Steel City" of Odisha, home to the Rourkela Steel Plant (RSP), one of India''s largest steel plants.'),
(NULL, 'The famous Simlipal National Park is located in which district?', 'Mayurbhanj', 'Keonjhar', 'Sundargarh', 'Deogarh', 'A', 1, 'Geography', 'medium', '["Simlipal", "National Park", "Mayurbhanj", "Wildlife"]'::jsonb, 'Simlipal National Park, a tiger reserve and biosphere reserve, is located in Mayurbhanj district and is known for its rich biodiversity.'),
(NULL, 'Which river forms the boundary between Odisha and Andhra Pradesh?', 'Mahanadi', 'Godavari', 'Rushikulya', 'Vamsadhara', 'D', 1, 'Geography', 'hard', '["Rivers", "Geography", "Boundary", "Vamsadhara"]'::jsonb, 'The Vamsadhara River forms part of the boundary between Odisha and Andhra Pradesh before flowing into the Bay of Bengal.'),
(NULL, 'The city of Cuttack is located on the banks of which river?', 'Mahanadi', 'Brahmani', 'Kathajodi', 'Birupa', 'C', 1, 'Geography', 'medium', '["Cuttack", "Kathajodi", "Rivers", "Geography"]'::jsonb, 'Cuttack, the former capital of Odisha, is located on the banks of the Kathajodi River, a distributary of the Mahanadi River.'),

-- ============================================
-- Category 6: History
-- ============================================

(NULL, 'The ancient kingdom of Kalinga covered most of modern-day Odisha. What was the capital of Kalinga?', 'Tosali', 'Dantapura', 'Rajagriha', 'Pataliputra', 'A', 1, 'History', 'hard', '["Kalinga", "Ancient History", "Tosali", "Capital"]'::jsonb, 'Tosali (also spelled Toshali) was the capital of the ancient Kalinga kingdom, located near modern-day Bhubaneswar.'),
(NULL, 'Which dynasty ruled Odisha during the construction of the Konark Sun Temple?', 'Eastern Ganga Dynasty', 'Bhoi Dynasty', 'Keshari Dynasty', 'Somavamsi Dynasty', 'A', 1, 'History', 'medium', '["Eastern Ganga Dynasty", "Konark", "History", "Dynasties"]'::jsonb, 'The Eastern Ganga Dynasty, under King Narasimhadeva I, ruled Odisha during the 13th century when the Konark Sun Temple was built.'),
(NULL, 'The famous Kalinga War was fought in 261 BCE. Which modern city is closest to the battlefield?', 'Bhubaneswar', 'Cuttack', 'Puri', 'Berhampur', 'A', 1, 'History', 'medium', '["Kalinga War", "Ashoka", "Bhubaneswar", "History"]'::jsonb, 'The Kalinga War was fought near modern-day Bhubaneswar. The Dhauli hills, where Ashoka''s rock edicts are located, are near the battlefield.'),
(NULL, 'Who was the last independent king of Odisha before it came under British rule?', 'Mukunda Deva', 'Prataprudra Deva', 'Kapilendra Deva', 'Gajapati Purushottam Deva', 'A', 1, 'History', 'hard', '["Mukunda Deva", "History", "Odisha", "Kings"]'::jsonb, 'Mukunda Deva was the last independent king of Odisha. After his defeat in 1568, Odisha came under various rulers and eventually British rule.'),
(NULL, 'The famous Udayagiri and Khandagiri caves were built during which dynasty?', 'Chedi Dynasty', 'Satavahana Dynasty', 'Mauryan Dynasty', 'Gupta Dynasty', 'A', 1, 'History', 'hard', '["Udayagiri", "Khandagiri", "Caves", "Chedi Dynasty"]'::jsonb, 'The Udayagiri and Khandagiri caves near Bhubaneswar were built during the Chedi Dynasty (2nd-1st century BCE) as residential caves for Jain monks.'),
(NULL, 'Which famous battle in 1803 led to the British annexation of Odisha?', 'Battle of Plassey', 'Battle of Buxar', 'Battle of Puri', 'Battle of Cuttack', 'C', 1, 'History', 'hard', '["British Rule", "History", "Battle of Puri", "1803"]'::jsonb, 'The Battle of Puri in 1803, where the British defeated the Marathas, led to the British annexation of Odisha and the end of Maratha rule.'),

-- ============================================
-- Category 7: Food & Cuisine
-- ============================================

(NULL, 'Rasgulla, one of the most famous Odia sweets, is traditionally made from which ingredient?', 'Chhena (cottage cheese)', 'Khoya (milk solids)', 'Besan (gram flour)', 'Semolina', 'A', 1, 'Food & Cuisine', 'easy', '["Rasgulla", "Sweet", "Chhena", "Cuisine"]'::jsonb, 'Rasgulla is made from chhena (cottage cheese) and soaked in sugar syrup. It originated in Odisha and is now popular throughout India.'),
(NULL, 'Chhena Poda is a famous dessert from Odisha. What does "Poda" mean in Odia?', 'Sweet', 'Burnt', 'Soft', 'Fried', 'B', 1, 'Food & Cuisine', 'medium', '["Chhena Poda", "Dessert", "Cuisine", "Odisha"]'::jsonb, 'Chhena Poda means "burnt cheese" in Odia. It is a caramelized cheese dessert that is baked until it gets a brown, burnt appearance on top.'),
(NULL, 'Pakhala is a traditional Odia dish, especially popular during summer. How is it typically served?', 'Hot with vegetables', 'Cold with curd and spices', 'Fried with onions', 'Steamed with dal', 'B', 1, 'Food & Cuisine', 'easy', '["Pakhala", "Traditional Food", "Summer Dish", "Cuisine"]'::jsonb, 'Pakhala is fermented rice soaked in water, typically served cold with curd, green chilies, and sometimes with fried fish or vegetables.'),
(NULL, 'Dahibara Aloodum is a popular street food. In which city is it most famous?', 'Bhubaneswar', 'Cuttack', 'Puri', 'Rourkela', 'B', 1, 'Food & Cuisine', 'medium', '["Dahibara Aloodum", "Street Food", "Cuttack", "Cuisine"]'::jsonb, 'Dahibara Aloodum is a very popular street food in Cuttack, consisting of deep-fried lentil dumplings (dahibara) served with curd and spiced potato curry (aloodum).'),
(NULL, 'Which traditional Odia sweet is made by deep-frying chhena balls and soaking them in sugar syrup?', 'Rasgulla', 'Rasmalai', 'Chhena Gaja', 'Kheer', 'C', 1, 'Food & Cuisine', 'hard', '["Chhena Gaja", "Sweet", "Cuisine", "Odisha"]'::jsonb, 'Chhena Gaja is made by shaping chhena into rectangular pieces, deep-frying them, and then soaking in sugar syrup. It has a unique texture and taste.'),

-- ============================================
-- Category 8: Culture & Traditions
-- ============================================

(NULL, 'Jhoti Chita is a traditional floor art form. What material is traditionally used to draw Jhoti?', 'Colored powder', 'Rice paste', 'Turmeric paste', 'Chalk powder', 'B', 1, 'Culture & Traditions', 'medium', '["Jhoti Chita", "Floor Art", "Rangoli", "Traditions"]'::jsonb, 'Jhoti Chita is drawn using rice paste (pithau) mixed with water. It is a traditional floor art form, similar to Rangoli, used during festivals and auspicious occasions.'),
(NULL, 'Sambalpuri saree is a famous traditional attire. Which district is it primarily associated with?', 'Sambalpur', 'Bargarh', 'Sonepur', 'Balangir', 'B', 1, 'Culture & Traditions', 'medium', '["Sambalpuri Saree", "Traditional Attire", "Bargarh", "Handloom"]'::jsonb, 'Sambalpuri saree, known for its ikat (bandha) work, is primarily associated with Bargarh district, though it is also made in Sambalpur and other Western Odisha districts.'),
(NULL, 'The traditional "Mardala" is a percussion instrument. What type of instrument is it?', 'String instrument', 'Wind instrument', 'Percussion instrument (drum)', 'Brass instrument', 'C', 1, 'Culture & Traditions', 'medium', '["Mardala", "Musical Instrument", "Percussion", "Odissi"]'::jsonb, 'Mardala is a traditional percussion instrument (drum) of Odisha, essential to Odissi music and dance performances. It is played with hands.'),
(NULL, 'Which traditional Odia festival involves women applying alta (red dye) on their feet and enjoying swings?', 'Raja Parba', 'Nuakhai', 'Durga Puja', 'Kartika Purnima', 'A', 1, 'Culture & Traditions', 'easy', '["Raja Parba", "Alta", "Women Festival", "Traditions"]'::jsonb, 'During Raja Parba, women and girls apply alta (red dye) on their feet, wear new clothes, and enjoy swings, celebrating the fertility of Mother Earth.'),
(NULL, 'The traditional "Gotipua" performers are trained in which classical dance form?', 'Odissi', 'Bharatanatyam', 'Kathak', 'Kuchipudi', 'A', 1, 'Culture & Traditions', 'medium', '["Gotipua", "Odissi", "Dance", "Traditions"]'::jsonb, 'Gotipua performers are trained in Odissi dance techniques. The Gotipua tradition is considered a precursor to modern Odissi dance and helps preserve the classical form.'),

-- ============================================
-- Category 9: Music & Instruments
-- ============================================

(NULL, 'Which traditional Odia musical instrument is essential for Odissi dance performances?', 'Tabla', 'Mridangam', 'Mardala', 'Dhol', 'C', 1, 'Music & Instruments', 'medium', '["Mardala", "Musical Instrument", "Odissi", "Music"]'::jsonb, 'Mardala is the traditional percussion instrument of Odisha, essential for Odissi music and dance. It provides the rhythmic foundation for performances.'),
(NULL, 'Odissi music is one of the classical music traditions of India. What is its primary language?', 'Sanskrit', 'Odia', 'Hindi', 'Bengali', 'A', 1, 'Music & Instruments', 'hard', '["Odissi Music", "Classical Music", "Sanskrit", "Music"]'::jsonb, 'Odissi music, though from Odisha, primarily uses Sanskrit for its compositions, along with Odia. It is one of the classical music traditions of India.'),
(NULL, 'Which traditional folk music form of Odisha is performed during agricultural activities?', 'Dalkhai', 'Sambalpuri', 'Gotipua', 'Chaiti', 'A', 1, 'Music & Instruments', 'medium', '["Dalkhai", "Folk Music", "Western Odisha", "Music"]'::jsonb, 'Dalkhai is a traditional folk music and dance form from Western Odisha, often performed during agricultural activities and festivals.'),
(NULL, 'The "Jhumar" is a traditional folk dance with music. Which region of Odisha is it associated with?', 'Coastal Odisha', 'Western Odisha', 'Northern Odisha', 'Southern Odisha', 'B', 1, 'Music & Instruments', 'hard', '["Jhumar", "Folk Dance", "Western Odisha", "Music"]'::jsonb, 'Jhumar is a traditional folk dance and music form from Western Odisha, particularly popular in the Sambalpur region, performed during festivals.'),

-- ============================================
-- Category 10: Handicrafts
-- ============================================

(NULL, 'Silver filigree work, known as "Tarakasi", is a famous handicraft. Which city is it primarily associated with?', 'Cuttack', 'Puri', 'Bhubaneswar', 'Berhampur', 'A', 1, 'Handicrafts', 'medium', '["Silver Filigree", "Tarakasi", "Cuttack", "Handicrafts"]'::jsonb, 'Silver filigree work, known as Tarakasi, is a famous handicraft of Cuttack, where artisans create intricate designs using fine silver wires.'),
(NULL, 'Applique work is famous in which town of Odisha?', 'Pipili', 'Raghurajpur', 'Cuttack', 'Puri', 'A', 1, 'Handicrafts', 'easy', '["Applique", "Pipili", "Handicrafts", "Odisha"]'::jsonb, 'Pipili is famous for its applique work, where artisans create beautiful designs by cutting and stitching colored cloth pieces, used for umbrellas, canopies, and decorative items.'),
(NULL, 'Stone carving is a traditional art form. Which temple city is particularly known for this craft?', 'Puri', 'Konark', 'Bhubaneswar', 'All of the above', 'D', 1, 'Handicrafts', 'medium', '["Stone Carving", "Handicrafts", "Temples", "Odisha"]'::jsonb, 'Stone carving is a traditional art form practiced in the temple cities of Puri, Konark, and Bhubaneswar, where artisans create sculptures and decorative items.'),
(NULL, 'The traditional "Pattachitra" paintings are created in which village near Puri?', 'Raghurajpur', 'Pipili', 'Danda', 'Konark', 'A', 1, 'Handicrafts', 'medium', '["Pattachitra", "Raghurajpur", "Painting", "Handicrafts"]'::jsonb, 'Raghurajpur, a heritage village near Puri, is famous for Pattachitra paintings, where entire families are involved in creating these traditional artworks.'),

-- ============================================
-- Category 11: Wildlife & Nature
-- ============================================

(NULL, 'Bhitarkanika National Park is famous for which species?', 'Royal Bengal Tiger', 'Saltwater Crocodile', 'One-horned Rhinoceros', 'Asian Elephant', 'B', 1, 'Wildlife & Nature', 'medium', '["Bhitarkanika", "National Park", "Crocodile", "Wildlife"]'::jsonb, 'Bhitarkanika National Park in Kendrapara district is famous for its population of saltwater crocodiles and is one of the largest mangrove ecosystems in India.'),
(NULL, 'Chilika Lake is a haven for migratory birds. Which bird is the most famous visitor?', 'Flamingo', 'Pelican', 'Siberian Crane', 'All of the above', 'D', 1, 'Wildlife & Nature', 'medium', '["Chilika Lake", "Migratory Birds", "Wildlife", "Puri"]'::jsonb, 'Chilika Lake attracts various migratory birds including flamingos, pelicans, and many other species, making it one of the largest wintering grounds for birds in India.'),
(NULL, 'Simlipal National Park is a tiger reserve. What does "Simlipal" mean?', 'Land of red silk cotton trees', 'Land of tigers', 'Land of elephants', 'Land of hills', 'A', 1, 'Wildlife & Nature', 'hard', '["Simlipal", "National Park", "Tiger Reserve", "Wildlife"]'::jsonb, 'Simlipal gets its name from the Simul (red silk cotton) trees that are abundant in the area. It is a tiger reserve and biosphere reserve in Mayurbhanj district.'),

-- ============================================
-- Category 12: Famous Personalities
-- ============================================

(NULL, 'Who is known as the "Utkal Gaurav" (Pride of Odisha) and was a key figure in the formation of Odisha as a separate state?', 'Madhusudan Das', 'Gopabandhu Das', 'Fakir Mohan Senapati', 'Utkalmani Gopabandhu Das', 'A', 1, 'Famous Personalities', 'hard', '["Madhusudan Das", "Utkal Gaurav", "Odisha State", "Personalities"]'::jsonb, 'Madhusudan Das (1848-1934) is known as "Utkal Gaurav" and played a crucial role in the formation of Odisha as a separate state and various social reforms.'),
(NULL, 'Which famous Odia freedom fighter and social reformer is known as "Utkalmani" (Jewel of Odisha)?', 'Gopabandhu Das', 'Madhusudan Das', 'Fakir Mohan Senapati', 'Radhanath Ray', 'A', 1, 'Famous Personalities', 'medium', '["Gopabandhu Das", "Utkalmani", "Freedom Fighter", "Personalities"]'::jsonb, 'Gopabandhu Das (1877-1928) is known as "Utkalmani" (Jewel of Odisha). He was a freedom fighter, social reformer, and key figure in Odisha''s independence movement.'),
(NULL, 'Who is the first Odia to receive the Jnanpith Award, India''s highest literary honor?', 'Gopinath Mohanty', 'Sachidananda Routray', 'Pratibha Ray', 'Binod Chandra Nayak', 'A', 1, 'Famous Personalities', 'hard', '["Gopinath Mohanty", "Jnanpith Award", "Literature", "Personalities"]'::jsonb, 'Gopinath Mohanty (1914-1991) was the first Odia writer to receive the Jnanpith Award in 1973 for his contribution to Odia literature.');

