-- Sample Odisha Culture MCQ Questions for Question Bank
-- This file contains sample questions covering various aspects of Odisha's culture, traditions, history, geography, festivals, temples, language, and arts
-- Run this in your Supabase SQL Editor to populate the question bank
-- All questions have exam_id = NULL, making them available for use in any exam

-- Temples & Architecture Questions
INSERT INTO questions (exam_id, question_text, option_a, option_b, option_c, option_d, correct_answer, points, category, difficulty_level, tags, explanation) VALUES
(NULL, 'The Konark Sun Temple, also known as the "Black Pagoda", was built during which dynasty?', 'Ganga Dynasty', 'Suryavanshi Dynasty', 'Chola Dynasty', 'Pala Dynasty', 'A', 1, 'Temples & Architecture', 'medium', '["Konark", "Temples", "History", "Architecture"]'::jsonb, 'The Konark Sun Temple was built in the 13th century CE by King Narasimhadeva I of the Eastern Ganga Dynasty.'),
(NULL, 'Which temple in Odisha is known as the "White Pagoda"?', 'Konark Sun Temple', 'Jagannath Temple, Puri', 'Lingaraj Temple, Bhubaneswar', 'Mukteswar Temple', 'B', 1, 'Temples & Architecture', 'easy', '["Jagannath", "Puri", "Temples"]'::jsonb, 'The Jagannath Temple in Puri is called the "White Pagoda" while Konark is called the "Black Pagoda".'),
(NULL, 'The Lingaraj Temple in Bhubaneswar is dedicated to which deity?', 'Lord Vishnu', 'Lord Shiva', 'Lord Krishna', 'Goddess Durga', 'B', 1, 'Temples & Architecture', 'medium', '["Lingaraj", "Bhubaneswar", "Temples", "Shiva"]'::jsonb, 'Lingaraj Temple is dedicated to Lord Shiva and is one of the oldest temples in Bhubaneswar, dating back to the 11th century.'),
(NULL, 'How many wheels are carved on the chariot of the Konark Sun Temple?', '12 wheels', '18 wheels', '24 wheels', '30 wheels', 'C', 1, 'Temples & Architecture', 'hard', '["Konark", "Architecture", "Sun Temple"]'::jsonb, 'The Konark Sun Temple is designed as a massive chariot with 24 elaborately carved stone wheels, representing the 24 hours of a day.'),

-- Festivals Questions
(NULL, 'Rath Yatra is celebrated in which month of the Odia calendar?', 'Baisakha', 'Jyestha', 'Ashadha', 'Shravana', 'C', 1, 'Festivals', 'easy', '["Rath Yatra", "Jagannath", "Puri", "Festivals"]'::jsonb, 'Rath Yatra is celebrated in the month of Ashadha (June-July) and is one of the most important festivals in Odisha.'),
(NULL, 'Nuakhai is a harvest festival celebrated primarily in which region of Odisha?', 'Coastal Odisha', 'Western Odisha', 'Northern Odisha', 'Southern Odisha', 'B', 1, 'Festivals', 'medium', '["Nuakhai", "Harvest Festival", "Western Odisha"]'::jsonb, 'Nuakhai is primarily celebrated in Western Odisha, especially in districts like Sambalpur, Bargarh, and Sundargarh.'),
(NULL, 'Raja Parba is a unique festival of Odisha that celebrates what?', 'Harvest season', 'Menstruation and fertility of Earth', 'Monsoon arrival', 'New Year', 'B', 1, 'Festivals', 'medium', '["Raja Parba", "Fertility Festival", "Women Festival"]'::jsonb, 'Raja Parba is a three-day festival celebrating menstruation and fertility of Mother Earth. During this time, the earth is believed to be menstruating and is given rest.'),
(NULL, 'During Durga Puja in Odisha, which goddess is worshipped in most households?', 'Maa Durga', 'Maa Kali', 'Maa Lakshmi', 'Maa Saraswati', 'A', 1, 'Festivals', 'easy', '["Durga Puja", "Goddess Durga", "Festivals"]'::jsonb, 'Durga Puja is celebrated with great enthusiasm in Odisha, where Maa Durga is worshipped in homes and pandals.'),

-- Language & Literature Questions
(NULL, 'Which of these is the classical language recognized by the Government of India and is the official language of Odisha?', 'Odia', 'Sanskrit', 'Pali', 'Prakrit', 'A', 1, 'Language & Literature', 'easy', '["Odia Language", "Classical Language", "Literature"]'::jsonb, 'Odia (also spelled Odia) is recognized as a classical language by the Government of India and is the official language of Odisha.'),
(NULL, 'Who is known as the "Kabi Samrat" (Emperor of Poets) of Odisha?', 'Fakir Mohan Senapati', 'Radhanath Ray', 'Upendra Bhanja', 'Gangadhar Meher', 'C', 1, 'Language & Literature', 'hard', '["Poetry", "Literature", "Upendra Bhanja"]'::jsonb, 'Upendra Bhanja is known as "Kabi Samrat" and is one of the greatest poets in Odia literature, famous for his kavya poetry.'),
(NULL, 'Which famous Odia novel by Fakir Mohan Senapati is considered a masterpiece of Indian literature?', 'Chha Mana Atha Guntha', 'Basanti', 'Nirmala', 'Amada Bata', 'A', 1, 'Language & Literature', 'medium', '["Fakir Mohan Senapati", "Novel", "Literature"]'::jsonb, 'Chha Mana Atha Guntha (Six Acres and a Third) is a famous novel by Fakir Mohan Senapati, considered one of the finest works of Indian literature.'),
(NULL, 'The Odia Mahabharata was translated by which famous poet?', 'Sarala Das', 'Jagannath Das', 'Balaram Das', 'Achyutananda Das', 'A', 1, 'Language & Literature', 'hard', '["Mahabharata", "Sarala Das", "Translation", "Literature"]'::jsonb, 'Sarala Das translated the Mahabharata into Odia in the 15th century, making it accessible to the common people.'),

-- Traditional Arts Questions
(NULL, 'Odissi is a classical dance form that originated from which temple?', 'Konark Sun Temple', 'Jagannath Temple, Puri', 'Lingaraj Temple', 'Mukteswar Temple', 'B', 1, 'Traditional Arts', 'medium', '["Odissi Dance", "Classical Dance", "Puri"]'::jsonb, 'Odissi dance originated from the Jagannath Temple in Puri, where temple dancers called Maharis performed devotional dances.'),
(NULL, 'Pattachitra is a traditional art form of Odisha. What does "Patta" mean?', 'Canvas', 'Painting', 'Story', 'Cloth', 'A', 1, 'Traditional Arts', 'medium', '["Pattachitra", "Traditional Art", "Painting"]'::jsonb, 'Pattachitra means "painting on cloth" where "Patta" means canvas or cloth and "Chitra" means painting.'),
(NULL, 'Gotipua is a traditional dance form of Odisha performed by whom?', 'Young girls', 'Young boys dressed as girls', 'Adult women', 'Adult men', 'B', 1, 'Traditional Arts', 'medium', '["Gotipua", "Dance", "Traditional"]'::jsonb, 'Gotipua is performed by young boys who dress as girls. This dance form is considered a precursor to Odissi dance.'),
(NULL, 'Which traditional Odia art form involves intricate palm leaf engravings?', 'Pattachitra', 'Talapatra Chitra', 'Stone carving', 'Wood carving', 'B', 1, 'Traditional Arts', 'hard', '["Palm Leaf", "Talapatra", "Traditional Art"]'::jsonb, 'Talapatra Chitra involves intricate engravings on palm leaves, a traditional art form that dates back centuries in Odisha.'),

-- Geography Questions
(NULL, 'Which is the largest district in Odisha by area?', 'Mayurbhanj', 'Sundargarh', 'Koraput', 'Malkangiri', 'A', 1, 'Geography', 'medium', '["Districts", "Geography", "Mayurbhanj"]'::jsonb, 'Mayurbhanj is the largest district in Odisha by area, known for Simlipal National Park and rich tribal culture.'),
(NULL, 'Which river is known as the "Mahanadi" and is the longest river in Odisha?', 'Brahmani', 'Subarnarekha', 'Mahanadi', 'Baitarani', 'C', 1, 'Geography', 'easy', '["Rivers", "Mahanadi", "Geography"]'::jsonb, 'Mahanadi is the longest river flowing through Odisha, originating in Chhattisgarh and emptying into the Bay of Bengal.'),
(NULL, 'Chilika Lake, the largest brackish water lagoon in India, is located in which district?', 'Puri', 'Ganjam', 'Khordha', 'Cuttack', 'A', 1, 'Geography', 'medium', '["Chilika Lake", "Puri", "Geography", "Lakes"]'::jsonb, 'Chilika Lake, Asia''s largest brackish water lagoon, is located primarily in Puri district and is a haven for migratory birds.'),
(NULL, 'Which mountain range runs through Western Odisha?', 'Eastern Ghats', 'Western Ghats', 'Vindhya Range', 'Satpura Range', 'A', 1, 'Geography', 'hard', '["Mountains", "Eastern Ghats", "Geography"]'::jsonb, 'The Eastern Ghats mountain range runs through Western Odisha, providing the region with diverse topography and mineral resources.'),

-- History Questions
(NULL, 'The famous Kalinga War was fought between Emperor Ashoka and the Kalinga Kingdom in which year?', '261 BCE', '273 BCE', '232 BCE', '250 BCE', 'A', 1, 'History', 'medium', '["Kalinga War", "Ashoka", "History"]'::jsonb, 'The Kalinga War was fought in 261 BCE. The massive bloodshed in this war led Emperor Ashoka to embrace Buddhism and non-violence.'),
(NULL, 'Which ancient kingdom covered most of modern-day Odisha?', 'Kalinga', 'Magadha', 'Kosala', 'Avanti', 'A', 1, 'History', 'easy', '["Kalinga", "Ancient Kingdom", "History"]'::jsonb, 'The ancient kingdom of Kalinga covered most of modern-day Odisha and parts of Andhra Pradesh and Chhattisgarh.'),
(NULL, 'The famous rock edicts of Ashoka were found in which place in Odisha?', 'Dhauli', 'Khandagiri', 'Udayagiri', 'Bhubaneswar', 'A', 1, 'History', 'medium', '["Ashoka", "Dhauli", "Rock Edicts", "History"]'::jsonb, 'The famous Dhauli rock edicts near Bhubaneswar contain the teachings of Emperor Ashoka after the Kalinga War.'),
(NULL, 'Which dynasty built the Konark Sun Temple?', 'Ganga Dynasty', 'Suryavanshi Dynasty', 'Bhoi Dynasty', 'Keshari Dynasty', 'A', 1, 'History', 'hard', '["Ganga Dynasty", "Konark", "History"]'::jsonb, 'The Eastern Ganga Dynasty, under King Narasimhadeva I, built the magnificent Konark Sun Temple in the 13th century.'),

-- Food & Cuisine Questions
(NULL, 'Which traditional Odia sweet is made from chhena (cottage cheese) and soaked in sugar syrup?', 'Rasgulla', 'Rasmalai', 'Chhena Poda', 'Kheer', 'A', 1, 'Food & Cuisine', 'easy', '["Rasgulla", "Sweet", "Cuisine", "Food"]'::jsonb, 'Rasgulla, made from chhena, originated in Odisha and is one of the most popular Odia sweets, though it''s now famous across India.'),
(NULL, 'Chhena Poda is a famous dessert from Odisha. What does "Poda" mean in Odia?', 'Sweet', 'Burnt', 'Soft', 'Fried', 'B', 1, 'Food & Cuisine', 'medium', '["Chhena Poda", "Dessert", "Cuisine"]'::jsonb, 'Chhena Poda means "burnt cheese" in Odia. It''s a caramelized cheese dessert that''s unique to Odisha.'),
(NULL, 'Dahibara Aloodum is a popular street food in which city of Odisha?', 'Bhubaneswar', 'Cuttack', 'Puri', 'Rourkela', 'B', 1, 'Food & Cuisine', 'medium', '["Street Food", "Cuttack", "Cuisine"]'::jsonb, 'Dahibara Aloodum is a very popular street food in Cuttack, consisting of deep-fried lentil dumplings served with curd and spiced potato curry.'),
(NULL, 'Pakhala is a traditional Odia dish made from what?', 'Rice', 'Wheat', 'Lentils', 'Corn', 'A', 1, 'Food & Cuisine', 'easy', '["Pakhala", "Rice", "Traditional Food"]'::jsonb, 'Pakhala is fermented rice soaked in water, a traditional dish of Odisha, especially popular during summer months.'),

-- Culture & Traditions Questions
(NULL, 'Which traditional Odia attire is worn by women during festivals and special occasions?', 'Saree', 'Lehenga', 'Salwar Kameez', 'Kurta', 'A', 1, 'Culture & Traditions', 'easy', '["Traditional Attire", "Saree", "Culture"]'::jsonb, 'The traditional Odia saree, particularly the Sambalpuri and Bomkai sarees, are worn by women during festivals and special occasions.'),
(NULL, 'The traditional "Danda Nacha" is a folk dance form of which region in Odisha?', 'Coastal Odisha', 'Western Odisha', 'Northern Odisha', 'Southern Odisha', 'B', 1, 'Culture & Traditions', 'medium', '["Danda Nacha", "Folk Dance", "Western Odisha"]'::jsonb, 'Danda Nacha is a traditional folk dance form of Western Odisha, performed during religious festivals.'),
(NULL, 'Which is the traditional musical instrument of Odisha, often used in Odissi music?', 'Tabla', 'Mridangam', 'Mardala', 'Dhol', 'C', 1, 'Culture & Traditions', 'hard', '["Music", "Mardala", "Odissi", "Instruments"]'::jsonb, 'Mardala is the traditional percussion instrument of Odisha, essential to Odissi music and dance performances.'),
(NULL, 'The traditional art of "Jhoti Chita" is used for what purpose?', 'Wall decoration', 'Storytelling', 'Religious rituals', 'Floor decoration', 'D', 1, 'Culture & Traditions', 'medium', '["Jhoti Chita", "Rangoli", "Floor Art", "Traditions"]'::jsonb, 'Jhoti Chita is traditional floor art (similar to Rangoli) drawn using rice paste, used for decoration during festivals and auspicious occasions.'),

-- Additional Questions
(NULL, 'How many districts are there in Odisha as of 2024?', '28 districts', '30 districts', '32 districts', '35 districts', 'B', 1, 'Geography', 'medium', '["Districts", "Geography", "Administrative"]'::jsonb, 'Odisha currently has 30 districts, which were reorganized over the years for better administrative management.'),
(NULL, 'Which UNESCO World Heritage Site is located in Odisha?', 'Konark Sun Temple', 'Jagannath Temple', 'Lingaraj Temple', 'Mukteswar Temple', 'A', 1, 'Temples & Architecture', 'easy', '["UNESCO", "World Heritage", "Konark"]'::jsonb, 'The Konark Sun Temple is a UNESCO World Heritage Site, recognized for its exceptional architectural and artistic significance.'),
(NULL, 'The famous "Mukteswar Dance Festival" is held at which temple?', 'Mukteswar Temple', 'Lingaraj Temple', 'Rajrani Temple', 'Parasurameswar Temple', 'A', 1, 'Festivals', 'medium', '["Mukteswar Temple", "Dance Festival", "Culture"]'::jsonb, 'The Mukteswar Dance Festival is an annual event held at the Mukteswar Temple in Bhubaneswar, showcasing classical Indian dance forms.');

